# Generated by Django 4.2.7 on 2025-12-22 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('course_type', models.CharField(choices=[('variables', 'Variables et instructions de base'), ('conditionals', 'Instructions conditionnelles'), ('loops', 'Structures itératives'), ('functions', 'Fonctions et procédures')], max_length=20, unique=True, verbose_name='Type de cours')),
                ('description', models.TextField(verbose_name='Description')),
                ('content', models.TextField(verbose_name='Contenu du cours')),
                ('importance', models.TextField(help_text='Pourquoi ce concept est important', verbose_name='Importance de ce concept')),
                ('when_to_use', models.TextField(help_text='Dans quelles situations utiliser ce concept', verbose_name='Quand utiliser')),
                ('possible_operations', models.TextField(help_text="Ce qu'on peut faire avec ce concept", verbose_name='Opérations possibles')),
                ('impossible_operations', models.TextField(help_text="Ce qu'on ne peut pas faire", verbose_name='Opérations impossibles')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('youtube_search_query', models.CharField(help_text='Terme de recherche pour les vidéos YouTube', max_length=200, verbose_name='Requête YouTube')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('question', models.TextField(verbose_name='Énoncé')),
                ('difficulty', models.CharField(choices=[('easy', 'Facile'), ('medium', 'Moyen'), ('hard', 'Difficile')], default='easy', max_length=10, verbose_name='Difficulté')),
                ('points', models.IntegerField(default=10, verbose_name='Points')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('option_a', models.CharField(max_length=500, verbose_name='Option A')),
                ('option_b', models.CharField(max_length=500, verbose_name='Option B')),
                ('option_c', models.CharField(blank=True, max_length=500, verbose_name='Option C')),
                ('option_d', models.CharField(blank=True, max_length=500, verbose_name='Option D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Réponse correcte')),
                ('explanation', models.TextField(help_text='Explication de la réponse correcte', verbose_name='Explication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='courses.course', verbose_name='Cours')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score obtenu')),
                ('max_score', models.IntegerField(verbose_name='Score maximum')),
                ('answer_given', models.CharField(max_length=1, verbose_name='Réponse donnée')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Réponse correcte ?')),
                ('attempt_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de tentative')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='courses.course', verbose_name='Cours')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='courses.exercise', verbose_name='Exercice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Score étudiant',
                'verbose_name_plural': 'Scores étudiants',
                'ordering': ['-attempt_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField(verbose_name='Commentaire')),
                ('feedback_type', models.CharField(choices=[('encouragement', 'Encouragement'), ('correction', 'Correction'), ('congratulation', 'Félicitation')], default='correction', max_length=20, verbose_name='Type de feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='courses.exercise', verbose_name='Exercice')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL, verbose_name='Encadreur')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks_received', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant')),
            ],
            options={
                'verbose_name': 'Commentaire encadreur',
                'verbose_name_plural': 'Commentaires encadreurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
